### PR TITLE
Add events domain

### LINKED ISSUE #6: Create Ash Domain for Events
Following are the resources to be created in the Events domain

### 1. EventDetails Table
- **EventID** (Primary Key): A unique identifier for each event.
- **EventName**: The name of the event.
- **Description**: A brief description of the event.
- **Location**: Where the event is taking place.
- **IsRecurring**: A boolean (true/false) indicating whether the event repeats.
- **RecurringRule**: A string or a structured format that defines how the event repeats (daily, weekly, monthly, custom).
- **RecurringUntil**: A date till which the event will keep recurring. This can be null if the event continues indefinitely.
- **OrganizerID** (Foreign Key): Links to the Organizers table.

### 2. **Event Instances Table**
Every event (whether one-time or recurring) has at least one entry in the Event Instances table. This approach ensures that all event timing information is centralized, making it easier to manage and retrieve data.

- **EventInstanceID** (Primary Key): Unique identifier for each instance of an event.
- **EventID** (Foreign Key): Links to the Events table.
- **StartTime**: Start time and date of the instance in UTC.
- **EndTime**: End time and date of the instance in UTC.
- **LocationOverride**: Optional field if the location varies from the main event location.

### 3. **Ticket Types Table**
Defines types of tickets available for events. Quantity of tickets is managed at an instance level.

- **TicketTypeID** (Primary Key): Unique identifier for each type of ticket.
- **EventID** (Foreign Key): Links to the Events table.
- **Type**: Name of the ticket type (e.g., VIP, General Admission).
- **Description**: Description of the ticket type.
- **Price**: The price of each ticket type.
- **Currency**: The currency of price.
- **Quantity**: The total quantity of tickets available for this ticket type.

### 4. **Ticket Purchases Table**
Records each ticket sale, linking it to a buyer and the specific instance of an event.

- **PurchaseID** (Primary Key): Unique identifier for each purchase.
- **TicketTypeID** (Foreign Key): Links to the TicketsType table.
- **UserID** (Foreign Key): Identifier for the user who purchased the ticket.
- **PurchaseDate**: The date and time the purchase was made in UTC.
- **Quantity**: Number of tickets purchased in this transaction.
- **Additional fields**: Additional fields to be added later to accommodate payment related details from Stripe or other gateways.

### 5. **User Preferences Table**
Stores information about users, including their preferred timezone for displaying event times.

- **UserPreferenceID** (Primary Key): Unique identifier for each user.
- **Name**: User's full name.
- **Email**: Email address of the user.
- **TimeZone**: Preferred timezone of the user for viewing event times.

### 6. **Organizers Table**
All events to be linked to an organiser.
- **OrganizerID** (Primary Key): Unique identifier for each organizer.
- **Name**: The name of the organizer.
- **Email**: Email address of the organizer.
- **ContactInfo**: Contact details of the organizer.

### 7. **Participants Table**
- **ParticipantID** (Primary Key): A unique identifier for each participant.
- **EventID** (Foreign Key): Linked to the Events table, indicating which event this is regarding.
- **UserID** (Foreign Key): Linked to a Users table, identifying the participant.
- **EventInstanceID** (Foreign Key): Linked to the Event Instances table.
- **TicketTypeID** (Foreign Key): Linked to the TicketTypes table, if the event requires a ticket to be purchased.
- **RSVPStatus**: Stores the RSVP status (e.g., 'Attending', 'Maybe', 'Not Attending').
- **RSVPDate**: The date and time when the RSVP was made or last updated.

### PR DESCRIPTION
**Pull request by shankardevy**
Fixes #6

### CODE REVIEW

**Comment by shankardevy** [comment]
I would say only this commit needs review: https://github.com/Collective-Commit/muhurta/pull/7/commits/aae616e7a1a24a9825e81782f8fc5d631b2add24

rest of the commits in this PR have generated code.

**Review by nittin-shankar — CHANGES_REQUESTED** [review]
@shankardevy Please check my comments on the commit https://github.com/Collective-Commit/muhurta/pull/7/commits/aae616e7a1a24a9825e81782f8fc5d631b2add24 that requires review. 

Additionally, I found out this commit https://github.com/Collective-Commit/muhurta/pull/7/commits/ca6c05e531ba95843af3837437e3a6b6f5c43f7b also needed my attention in order to get a full picture. Everything in it seems pretty good 😄

**Review by nittin-shankar — COMMENTED** [review]
Good job! However, there's [this](https://github.com/Collective-Commit/muhurta/commit/aae616e7a1a24a9825e81782f8fc5d631b2add24#r141352998) comment of yours that I don't understand properly. Please look into it and get back to me 😄

**Comment by shankardevy** [comment]
@nittin-shankar I have removed the duplicated fields in the subsequent commit.

**Review by nittin-shankar — APPROVED** [review]
🌸

**Pull request merged**
